export const menuItems = [
  {
    title: "News",
    href: "/news",
    subItems: [
      { title: "Breaking News", href: "/news/breaking" },
      { title: "National", href: "/news/national" },
      { title: "International", href: "/news/international" },
      { title: "Most Read", href: "/news/most-read" },
      { title: "Trending", href: "/news/trending" },
    ],
  },
  {
    title: "Politics",
    href: "/politics",
    subItems: [
      { title: "Government", href: "/politics/government" },
      { title: "Elections", href: "/politics/elections" },
      { title: "Policy", href: "/politics/policy" },
      { title: "Political Parties", href: "/politics/parties" },
      { title: "Analysis", href: "/politics/analysis" },
    ],
  },
  {
    title: "Diplomacy",
    href: "/diplomacy",
    subItems: [
      { title: "Foreign Affairs", href: "/diplomacy/foreign-affairs" },
      {
        title: "International Relations",
        href: "/diplomacy/international-relations",
      },
      { title: "Embassy News", href: "/diplomacy/embassy" },
      { title: "Treaties & Agreements", href: "/diplomacy/treaties" },
    ],
  },
  {
    title: "Court & Crime",
    href: "/court-crime",
    subItems: [
      { title: "Court Cases", href: "/court-crime/cases" },
      { title: "Crime Reports", href: "/court-crime/reports" },
      { title: "Legal Analysis", href: "/court-crime/analysis" },
      { title: "Police Updates", href: "/court-crime/police" },
    ],
  },
  {
    title: "Counties",
    href: "/counties",
    subItems: [
      { title: "Nairobi", href: "/counties/nairobi" },
      { title: "Mombasa", href: "/counties/mombasa" },
      { title: "Kisumu", href: "/counties/kisumu" },
      { title: "All Counties", href: "/counties" },
      { title: "Devolution", href: "/counties/devolution" },
    ],
  },
  {
    title: "Health",
    href: "/health",
    subItems: [
      { title: "Healthcare News", href: "/health/news" },
      { title: "Medical Research", href: "/health/research" },
      { title: "Public Health", href: "/health/public" },
      { title: "Wellness", href: "/health/wellness" },
    ],
  },
  {
    title: "Business",
    href: "/business",
    subItems: [
      { title: "Markets", href: "/business/markets" },
      { title: "Finance", href: "/business/finance" },
      { title: "Tech", href: "/business/tech" },
      { title: "Agriculture", href: "/business/agriculture" },
      { title: "Entrepreneurship", href: "/business/entrepreneurship" },
    ],
  },
  {
    title: "Sports",
    href: "/sports",
    subItems: [
      {
        title: "Football",
        href: "/sports/football",
        subItems: [
          { title: "KPL", href: "/sports/football/kpl" },
          { title: "FKF Cup", href: "/sports/football/fkf-cup" },
          { title: "EPL", href: "/sports/football/epl" },
          { title: "FA Cup", href: "/sports/football/fa-cup" },
          { title: "Serie A", href: "/sports/football/serie-a" },
          { title: "Bundesliga", href: "/sports/football/bundesliga" },
          { title: "Ligue 1", href: "/sports/football/ligue-1" },
          { title: "La Liga", href: "/sports/football/la-liga" },
          { title: "PSL", href: "/sports/football/psl" },
          { title: "UEFA Champions League", href: "/sports/football/ucl" },
          { title: "CAF Champions League", href: "/sports/football/caf-cl" },
          { title: "Europa League", href: "/sports/football/europa" },
          {
            title: "UEFA Conference League",
            href: "/sports/football/uefa-conference",
          },
          {
            title: "CAF Confederations Cup",
            href: "/sports/football/caf-confed",
          },
          { title: "CHAN", href: "/sports/football/chan" },
          { title: "AFCON", href: "/sports/football/afcon" },
          { title: "Fixtures & Results", href: "/sports/football/fixtures" },
          { title: "Tables", href: "/sports/football/tables" },
        ],
      },
      { title: "Athletics", href: "/sports/athletics" },
      { title: "Basketball", href: "/sports/basketball" },
      { title: "Golf", href: "/sports/golf" },
      { title: "Tennis", href: "/sports/tennis" },
      { title: "Rugby", href: "/sports/rugby" },
      { title: "Volleyball", href: "/sports/volleyball" },
      { title: "Motorsport", href: "/sports/motorsport" },
      { title: "Formula One", href: "/sports/formula-one" },
      { title: "Live Scores", href: "/sports/live-scores", isLive: true },
    ],
  },
  {
    title: "Lifestyle",
    href: "/lifestyle",
    subItems: [
      { title: "Celebrity Watch", href: "/lifestyle/celebrity" },
      { title: "Fashion", href: "/lifestyle/fashion" },
      { title: "Entertainment", href: "/lifestyle/entertainment" },
      { title: "Relationships", href: "/lifestyle/relationships" },
      { title: "Culture", href: "/lifestyle/culture" },
    ],
  },
  {
    title: "Opinion",
    href: "/opinion",
    subItems: [
      { title: "Editorials", href: "/opinion/editorials" },
      { title: "Columns", href: "/opinion/columns" },
      { title: "Letters", href: "/opinion/letters" },
      { title: "Analysis", href: "/opinion/analysis" },
    ],
  },
];
